name: Docker Image CI

on:
  push:
    branches: [ "main", "patch-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #       registry: ghcr.io
    #       username: "hargata"
    #       password: "${{ secrets.GHCR_PAT }}"
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ghcr.io/hargata/lubelogger:latest
