name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Setup Native Nodes for Docker BuildX
      run: |
	  docker buildx create --use --name mybuild node-amd64
          docker buildx create --append --name mybuild node-arm64
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: "hargata"
          password: "${{ secrets.GHCR_PAT }}"
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/hargata/lubelogger:latest