name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker login -u "hargata" -p "${{ secrets.GHCR_PAT }}" ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/hargata/lubelogger:latest
        docker push ghcr.io/hargata/lubelogger:latest